spring:
  application:
    name: rsp01

  cloud:
    compatibility-verifier:
      enabled: false

  boot:
    admin:
      client:
        url: http://localhost:1414/

server:
  port: 8484

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/