spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dining_db
    username: "root"
    password: "projectK"
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    enabled: true
  thymeleaf:
    enabled: true

spring.mvc.view.prefix: '/templates/'
spring.mvc.view.suffix: .html


tablereservation:
  reservationStartTime: 11
  reservationEndTime: 20
  totalNumOfTable: 5
  timeZone: "America/Chicago"
  tableNumbers: 1,2,3,4,5
